

web_list = [
    "js",
    "layadccout",
    "libs",
    "res",
    "app_remote-c6c70141aa.json",
    "app-c6c70141aa.json",
    "Img_Login_Bg.jpg",
    "index.js",
    "languageLogin-8e474a07d8.json",
    "siteConfig.json",
    "version.zip",
            ]
# res_list = [
#     "/res/animation/equip/hunter_default_arms",
#     "/res/animation/equip/hunter_default_body",
#     "/res/animation/equip/hunter_default_body_cloak",
#     "/res/animation/equip/hunter_default_hair",
#     "/res/animation/equip/mystery_default_body",
#     "/res/animation/equip/warrior_default_arms",
#     "/res/animation/equip/warrior_default_body",
#     "/res/animation/equip/warrior_default_body_cloak",
#     "/res/animation/equip/warrior_default_cloak",
#     "/res/animation/equip/warrior_default_hair",
#     "/res/animation/equip/wizard_default_arms",
#     "/res/animation/equip/wizard_default_body",
#     "/res/animation/equip/wizard_default_hair",
#     "/res/animation/mapmaterial/land/10000",
#     "/res/animation/mapmaterial/land/10001",
#     "/res/animation/mapmaterial/land/10002",
#     "/res/animation/swf/avatar/hunter_default_arms",
#     "/res/animation/swf/avatar/hunter_default_arms_mount",
#     "/res/animation/swf/avatar/hunter_default_body",
#     "/res/animation/swf/avatar/hunter_default_body_cloak",
#     "/res/animation/swf/avatar/hunter_default_body_cloak_mount",
#     "/res/animation/swf/avatar/hunter_default_body_mount",
#     "/res/animation/swf/avatar/hunter_default_hairdown",
#     "/res/animation/swf/avatar/hunter_default_hairdown_mount",
#     "/res/animation/swf/avatar/hunter_default_hairup",
#     "/res/animation/swf/avatar/hunter_default_hairup_mount",
#     "/res/animation/swf/avatar/mount_armorhorse_default",
#     "/res/animation/swf/avatar/mount_horse_default",
#     "/res/animation/swf/avatar/mystery_default_body",
#     "/res/animation/swf/avatar/warrior_default_arms",
#     "/res/animation/swf/avatar/warrior_default_body",
#     "/res/animation/swf/avatar/warrior_default_body_cloak",
#     "/res/animation/swf/avatar/warrior_default_body_cloak_mount",
#     "/res/animation/swf/avatar/warrior_default_body_mount",
#     "/res/animation/swf/avatar/warrior_default_hairdown",
#     "/res/animation/swf/avatar/warrior_default_hairdown_mount",
#     "/res/animation/swf/avatar/warrior_default_hairup",
#     "/res/animation/swf/avatar/warrior_default_hairup_mount",
#     "/res/animation/swf/avatar/wizard_default_arms",
#     "/res/animation/swf/avatar/wizard_default_arms_mount",
#     "/res/animation/swf/avatar/wizard_default_body",
#     "/res/animation/swf/avatar/wizard_default_body_mount",
#     "/res/animation/swf/avatar/wizard_default_hairdown",
#     "/res/animation/swf/avatar/wizard_default_hairdown_mount",
#     "/res/animation/swf/avatar/wizard_default_hairup",
#     "/res/animation/swf/avatar/wizard_default_hairup_mount",
#     "/res/UI",
#     "/res/xml",
#
# ]
#


